[2025-09-30 11:05:58] [INFO    ] discord.client: logging in using static token
[2025-09-30 11:06:00] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 621576f2b3226dd0337d076f70753e42).
[2025-09-30 11:06:04] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command hello
Traceback (most recent call last):
  File "C:\Trial and Error\Discord Bot\lib\site-packages\discord\ext\commands\core.py", line 266, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\asust\Downloads\product-service\Discord Bot\main.py", line 32, in hello
    embed.set_image(url="https://cdn.discordapp.com/attachments/1354444598784557108/1422418681647992843/2_lah.jpg?ex=68dc9a20&is=68db48a0&hm=93659d3bb7fe2de2ec21bd2b424c240c67495e75bf5efbcf973a7dc68c5e3b9c&")
NameError: name 'embed' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Trial and Error\Discord Bot\lib\site-packages\discord\ext\commands\bot.py", line 1376, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Trial and Error\Discord Bot\lib\site-packages\discord\ext\commands\core.py", line 1064, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Trial and Error\Discord Bot\lib\site-packages\discord\ext\commands\core.py", line 275, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'embed' is not defined
